import Link from 'next/link';
import { listFunds } from '@/lib/data/funds';
import { listEntries } from '@/lib/data/entries';
import { money,month,pct } from '@/lib/format';
import { overview } from '@/lib/data/overview';
export default async function Dashboard({ searchParams }: { searchParams: Promise<{year?:string;deleted?:string}> }) {
  const [funds,entries] = await Promise.all([listFunds(),listEntries()]);
  const query = await searchParams;
  const years = [...new Set(entries.map(e => Number(e.period.slice(0,4))))].sort((a,b) => b-a);
  if (!years.length) years.push(new Date().getFullYear());
  const year = query.year && years.includes(Number(query.year)) ? Number(query.year) : years[0];
  const report = overview(funds,entries,year), top = report.cards.find(c => c.latest);
  const periods = [...new Set(report.cards.flatMap(c => c.latest ? [c.latest.period] : []))].sort();
  return <><div className="page-header"><div><p className="eyebrow">PORTFOLIO OVERVIEW</p><h1>Fund performance</h1><p className="subtitle">A clear view of your funds, month by month.</p></div><div className="header-actions"><a className="button secondary" href="/api/export">↓ Export CSV</a><Link className="button" href="/entries/new">＋ New entry</Link></div></div>
    {query.deleted && <p className="alert success" role="status">Fund deleted.</p>}
    <div className="report-toolbar"><p className="muted">Latest available per fund {periods.length > 0 && `· ${month(periods[0])}${periods.length > 1 ? ` – ${month(periods[periods.length-1])}` : ''}`}</p><form><label htmlFor="report-year">YTD year</label><select id="report-year" name="year" defaultValue={year}>{years.map(y => <option key={y}>{y}</option>)}</select><button className="secondary small">Apply</button></form></div>
    <div className="stats"><article><span>Portfolio closing value</span><strong>{money(report.closing)}</strong><small>Latest snapshot · {report.cards.filter(c => c.latest).length}/{funds.length} funds</small></article><article><span>Net return · latest snapshot</span><strong className={report.latestReturn < 0 ? 'negative' : 'positive'}>{money(report.latestReturn)}</strong><small>Sum of each fund’s latest month</small></article><article><span>YTD net return · {year}</span><strong className={report.ytd < 0 ? 'negative' : 'positive'}>{money(report.ytd)}</strong><small>Recorded months in selected year</small></article><article><span>Total outflow</span><strong>{money(report.outflow)}</strong><small>All recorded months</small></article></div>
    {top && <div className="leader-banner"><div className="leader-icon">↗</div><div><p className="eyebrow">TOP PERFORMER / LATEST MONTH</p><strong>{top.fund.name}</strong><p>{pct(top.latest.return_pct)} · {month(top.latest.period)}</p></div><Link href={`/funds/${top.fund.id}`} className="text-link">Review fund →</Link></div>}
    <div className="section-heading"><h2>Your funds <span className="count-badge">{funds.length}</span></h2><span className="muted">Ranked by latest return %</span></div>
    <div className="fund-grid">{report.cards.map(({fund:f,latest:e,ytd,outflow,flags:badges},index) => <article className={`fund-card ${e && index === 0 ? 'top-card' : ''}`} key={f.id}><div className="card-top"><span className="fund-code">{f.code}</span><span className="muted">{e ? month(e.period) : 'No entries'}</span></div><h2><Link href={`/funds/${f.id}`}>{f.name}</Link></h2>{e ? <><span className="value-label">CLOSING VALUE</span><div className="value">{money(e.closing_value)}</div><div className="return-line"><span className={e.net_return < 0 ? 'negative' : 'positive'}>{money(e.net_return)} <small>net return</small></span><span className={`return-pill ${e.return_pct < 0 ? 'negative' : 'positive'}`}>{pct(e.return_pct)}</span></div><dl className="card-metrics"><div><dt>YTD return · {year}</dt><dd className={ytd < 0 ? 'negative' : ''}>{money(ytd)}</dd></div><div><dt>Latest outflow</dt><dd>{money(e.outflow)}</dd></div><div><dt>Total outflow</dt><dd>{money(outflow)}</dd></div></dl><div className="badge-row">{badges.map(flag => <span key={flag} className={`flag ${flag === 'Outstanding' ? 'good' : ''}`}>{flag}</span>)}</div><div className="drivers"><span className="value-label">KEY CONTRIBUTORS</span><p>{e.key_contributors || 'No contributors recorded. Add context to this entry.'}</p></div></> : <div className="card-empty"><p>No entries yet.</p><Link href={`/entries/new?fund=${f.id}`} className="text-link">＋ Log the first month</Link></div>}<div className="card-footer"><Link href={`/funds/${f.id}`} className="text-link">View fund →</Link>{e && <Link href={`/entries/${e.id}/edit`} className="text-link">Edit latest</Link>}</div></article>)}</div>
    {!funds.length && <div className="empty"><h2>Create your first fund</h2><p>Add a fund, then log its monthly performance.</p><Link href="/funds/new" className="button">Add fund</Link></div>}
    <p className="page-footnote">Demo workspace · Values use one reporting currency. Returns exclude capital flows. Latest snapshots may span different reporting months.</p></>;
}
